version: "3.8"

services:
  weaviate:
    image: semitechnologies/weaviate:1.22.3
    ports:
      - "8080:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: "none"
    restart: unless-stopped

  rag-api:
    build: .
    container_name: rag-api
    ports:
      - "8000:8000"
    volumes:
      - ./data/images:/app/data/images
    depends_on:
      - weaviate
    environment:
      - FIFTYONE_DATABASE_DIR=/app/.fiftyone
    stdin_open: true
    tty: true 
    restart: unless-stopped

volumes:
  weaviate_data:
